package defaults

var ApiSpecYaml = []byte(`id:
  providerName: 'admin'
  version: ''
  apiName: ''
context: ''
contextTemplate: ''
type: HTTP
tags: []
availableTiers:
- name: 'Unlimited'
uriTemplates: []
status: CREATED
visibility: 'public'
transports: 'http,https'
implementation: 'ENDPOINT'
endpointConfig: '{"production_endpoints":{"url":"http://localhost:8080", "config":"null"}, "endpoint_type":"http"}'
`)

var ProjectReadme = []byte(`WSO2 API Manager Project

================================
Project structure
================================

├── Docs
│   └── FileContents # holds documents
├── Image
├── Meta-information
│   ├── api.json # information of API
│   └── swagger.json # swagger definition for API
├── README
└── Sequences # sequences
    ├── fault-sequence
    ├── in-sequence
    └── out-sequence

================================
Deploy a minimal API
================================

To deploy a minimal API once project generated open Meta-information/api.json and edit

- apiName : Must not include spaces (i.e. MyAPI)
- version : A simple version string (i.e. v1.0.0)
- context : Context of API in NAME/VERSION format (i.e. /MyAPI/v1.0.0)
- contextTemplate: Context template used for version API (i.e. /MyAPI/{version})

Meta-information/swagger.json contains a default swagger generated by tool.
You can replace it if you like.

import api as usual with
apimcli import-api [directory path]

================================
Publishing API Project
================================

Change status field in api.json from CREATED to PUBLISHED and import it`)

var Swagger = []byte(`{
  "paths": {
    "/*": {
      "get": {
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  },
  "swagger": "2.0"
}`)
