package defaults

var ApiSpecYaml = []byte(`id:
  providerName: 'admin'
  version: ''
  apiName: ''
context: ''
contextTemplate: ''
type: HTTP
tags: []
availableTiers:
- name: 'Unlimited'
uriTemplates: []
status: CREATED
visibility: 'public'
transports: 'http,https'
endpointConfig: '{"production_endpoints":{"url":"http://localhost:8080", "config":"null"}, "endpoint_type":"http"}'
`)

var ProjectReadme = []byte(`WSO2 API Manager Project

================================
Project structure
================================

├── api_params.yaml
├── Docs
│   └── FileContents
├── Image
├── Meta-information
│   ├── api.json
│   └── swagger.json
├── README.txt
└── Sequences
    ├── fault-sequence
    ├── in-sequence
    └── out-sequence

================================
Deploy a minimal API
================================

To deploy a minimal API once project generated open Meta-information/api.json and edit

- apiName : Must not include spaces (i.e. MyAPI)
- version : A simple version string (i.e. v1.0.0)
- context : Context of API (i.e. /MyAPI)

Meta-information/swagger.json contains a default swagger generated by tool.
Replace Meta-information/swagger.json with your swagger file.

Edit api_params.yml and add your endpoint specific URLs there.

import api as usual with
apimcli import-api [directory path]

================================
Publishing API Project
================================

Change status field in api.json from CREATED to PUBLISHED and import it
`)

var Swagger = []byte(`{
  "paths": {
    "/*": {
      "get": {
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  },
  "openapi": "3.0.0"
}`)

const ApiVarsTmpl = `environments:{{- range $name, $elem := . }}
  - name: {{ $name }}
    endpoints:
      production:
        url: ''
{{- end }}`
